<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-11UCV8M" failures="1" tests="8" name="tests.LoginTest" time="23.302" errors="0" timestamp="2025-07-27T17:36:29 IST" skipped="4">
  <testcase classname="tests.LoginTest" name="testLoginWithValidCredentials" time="2.724"/>
  <testcase classname="tests.LoginTest" name="testLoginWithLockedCredentials" time="2.042">
    <skipped/>
  </testcase> <!-- testLoginWithLockedCredentials -->
  <testcase classname="tests.LoginTest" name="testLoginWithInvalidCredentials" time="2.871"/>
  <testcase classname="tests.LoginTest" name="testLoginWithBlankCredentials" time="3.146">
    <skipped/>
  </testcase> <!-- testLoginWithBlankCredentials -->
  <testcase classname="tests.LoginTest" name="testLoginWithBlankCredentials" time="2.217">
    <skipped/>
  </testcase> <!-- testLoginWithBlankCredentials -->
  <testcase classname="tests.LoginTest" name="testLoginWithBlankCredentials" time="4.441">
    <failure message="Error message on the Login Page is incorrect. expected [Username Required] but found [Epic sadface: Username is required]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message on the Login Page is incorrect. expected [Username Required] but found [Epic sadface: Username is required]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.LoginTest.testLoginWithBlankCredentials(LoginTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testLoginWithBlankCredentials -->
  <testcase classname="tests.LoginTest" name="testLoginWithBlankCredentials" time="2.880">
    <skipped/>
  </testcase> <!-- testLoginWithBlankCredentials -->
  <testcase classname="tests.LoginTest" name="testLoginWithBlankxCredentials" time="2.981"/>
</testsuite> <!-- tests.LoginTest -->
